### ISSUE TITLE
Absolute Path in Windows

### ISSUE THREAD

**Issue by raviroshan** [emiljohansson/list-files#2]
Hi Emil,

I am getting Absolute Path in Windows instead of Relative.
@import "C:/Users/username/Workspace/FrontEnd/ProjectX/country-section";

The plugin works fine in Mac.
@import "./ProjectX/country-section";

**Comment by emiljohansson** [comment]
Hi @raviroshan,

Please update to v1.1.4 and let me know if it resolved the issue.

Thanks

**Comment by raviroshan** [comment]
@emiljohansson : Thank you for prompt response. After updating the package to 1.1.4, the complete build is breaking. 
Current Output : @import "./";

No File/Folder name is appended after './'
